baseurl = "https://intsuki.netlify.com" # Hostname (and path) to the root.
title = "Intsuki" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

[params] # theme parameters
    author = "Intsuki" # Author's name.
	authorAltName = "Peter Yuanzong Li" # Author's alternative name.
    info = "Programmer & Student" # Author's job title or info.
    description = "Intsuki's personal website" # Site description.
    keywords = "github,developer,personal" # Site keywords.
    avatarurl = "images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.
	
	footercontent = "© Intsuki 2018" # Add footer content

    # Custom CSS
    custom_css = ["css/custom.css"]

    # Alignment of Mobile Menu items
    itemscentered = true

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/yyIntsuki/"
[[params.social]]
    name = "Stack Overflow"
    weight = 2
    url = "https://stackoverflow.com/users/10417903/intsuki"
[[params.social]]
    name = "E-Mail"
    weight = 3
    url = "mailto:intsuki.yz@gmail.com"

# Menu links
#[[menu.main]]
#    name = "Blog"
#    weight = 1
#    url  = "posts"
[[menu.main]]
    name = "About"
    weight = 1
    url = "about"